### ISSUE TITLE
Can't connect to STC

### ISSUE THREAD

**Issue by talentwill** [Spirent/py-stcrestclient#14]
I try to connect to STC, but failed, how to troubleshoot this?  btw, I can ping this ip address, 
![connect-failed](https://user-images.githubusercontent.com/9908836/50816325-2f6af080-135b-11e9-96b9-2991de5db794.png)

**Comment by ajgillis** [comment]
To troubleshoot:
1. Make sure that the you have the correct target host and it is running the ReST API - Use a browser to access the ReST API on the host: http://10.97.115.76/stcapi  You should see a page that has **Api Root** and a list of API endpoints.  If you do not see that then you are not accessing the correct machine or something is blocking HTTP access to that address.

2.  If the host is a Lab Server, log into the host as `admin`.  Use the menu to see if the container is running: `[4] System Status` -> `[1] Docker`.  If the container is running, you should see something that looks like:
```
---- Containers ----
CONTAINER ID        IMAGE               STATUS
b237291d024c        d77446b2be8d        Up 22 hours

---- Images ----
IMAGE ID            REPOSITORY                         CREATED
d77446b2be8d        registry.oriontest.net/labserver   39 hours ago
```

Is it possible that there is some type of access filter or proxy between your client and the address your are trying to connect to?  This has been the most common cause of this type of situation.

**Comment by ajgillis** [comment]
Closing this as it appears to be an environment issue, not a problem with stcrestclient.
