### ISSUE TITLE
STC not tracking or deleting sessions correctly

### ISSUE THREAD

**Issue by aksiksi** [Spirent/py-stcrestclient#15]
# Environment

- STC 4.81.2726.0000
- Windows Server 2007 SP2
- stcrestclient 1.8.0, 1.8.1

# Issue

I'm facing an issue where either the API or the server is not tracking a session after it is created and is not removing it once `stc.end_session()` is called.

Minimum example:

```python
from stcrestclient import stchttp

stc = stchttp.StcHttp(server_ip, port=server_port)

stc.new_session('abc', 'test', kill_existing=True)

project = stc.create('project')

stc.connect(chassis_ip)
```

Now when I try to list sessions:

```
In [31]: stc.sessions()
Out[31]: ['test - abc']

In [32]: stc.sessions()
Out[32]: []

In [33]: stc.sessions()
Out[33]: ['roboxr - aksiksi']

In [34]: stc.sessions()
Out[34]: []

In [35]: stc.sessions()
Out[35]: []

In [36]: stc.sessions()
Out[36]: ['roboxr - aksiksi']
```

I get the same "random" output when accessing the REST API directly at `/stcapi/sessions`.

Ending the session does not help.  I also tried to restart the `stcweb` process but the issue persisted.  

How do I solve this? And will this issue impact creation and configuration of ports?

Thanks!

**Comment by ajgillis** [comment]
This is not a problem with stcrestclient.  This was an issue with other system/software, which has been resolved.
