### ISSUE TITLE
StreamBlock creation via command not working

### ISSUE THREAD

**Issue by KrobotP** [Spirent/py-stcrestclient#22]
Hello,

I am just trying to set up some stream blocks programatically and I just faced an error using your instructions in readme. When I connected to the STC and obtained a port handler I tried to create stream block using the command:

`sb_handle = stc.create('streamBlock', port_handle)`

This ended up with an error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: create() takes 2 positional arguments but 3 were given
```

Inspecting create() method in stcpythonrest.py I have found that the method works if I use it like this:

`sb_handle = stc.create('streamBlock', under=port_handle)`

However, this seems to me like kind of bypassing part of create() methods behavior. I am using Python 3.6.8. Am I doing something wrong?

**Comment by jmkho-spirent** [comment]
StcPythonRest emulates the native python bindings for the STC automation API so that it can be used as drop-in replacement without requiring changes to existing python code. Looking at the our API documentation, for the native bindings, it looks like the `under` keyword argument is needed. For StcHttp (what is referred to in the readme), that does not require the under keyword.

**Comment by KrobotP** [comment]
Thanks for your reply. I will keep that in my mind. Is it possible to read these nuances somewhere? I  found this one inspecting the code.

**Comment by jmkho-spirent** [comment]
The StcHttp module is the one documented in this repository for use as a client. Like I mentioned, StcPythonRest is meant to be a drop-in replacement for our native language bindings so familiarity with the existing Python bindings is somewhat assumed. The native API documentation is available on our support site at https://support.spirent.com/SpirentCSC/SpirentDownloadsAppPage?activeTab=download but will require a login. Chapter 23 of the Automation Programming Guide has the information on the Python API.

**Comment by KrobotP** [comment]
Ok, great. I have access to the docs so I will inspect the Python API docs. Cheers!
