### ISSUE TITLE
Test Center Server == LabServer?

### ISSUE THREAD

**Issue by hellt** [Spirent/py-stcrestclient#4]
Hello,
Does this client require Spirent [LabServer](https://docs.google.com/viewer?url=https://www.spirent.com/-/media/Datasheets/Broadband/PAB/SpirentTestCenter/Spirent_Virtual_LabServer_datasheet.pdf) to be installed?
In other words, if I have STCv, what are my options to use REST API agains the virtual chassis? LabServer only?

**Comment by songkamongkol** [comment]
yes, this client requires labServer. There is no other option for this client at the moment.

**Comment by aksiksi** [comment]
Is it still the case that the REST API requires LabServer? We're running STC v4.81 on a Windows box. Thanks.

**Comment by toddlaw** [comment]
You can now use STC’s REST API without LabServer.  It is called “stcweb”, and you can run it from a Windows box.
